version: '3.8'

services:
# Backend services in Flask
  backend-flask:
    environment:
      FRONTEND_URL: "*"
      BACKEND_URL: "*"
    build: ./backend-flask
    ports: 
    - "4567:4567"
    volumes:
    - ./backend-flask:/backend-flask

# Frontend Service in react
  frontend-react-js:
    environment:
      REACT_APP_BACKEND_URL: "http://127.0.0.1:4567"
    build: ./frontend-react-js
    ports:
      - "8080:80"
    volumes:
      - ./frontend-react-js:/frontend-react-js

# Bridge Network for container to communicate with each other

networks: 
  internal-network:
    driver: bridge
    name: cruddur